
# Trap them if GNU Make isn't being used

all:
	@echo ""
	@echo ""
	@echo "     You must have GNU Make to install IPW!"
	@echo ""
	@echo "     Please read the INSTALL file in this directory."
	@echo ""
	@echo ""

realclean clean test tests test-clean install export: all

