include $(IPW)/lib/make/Makestart

LIB=ipw

SRCS=\
	_bih.c _nohist.c bihcheck.c bihdup.c bihmake.c bihread.c bihwrite.c \
	hnbands.c hnbits.c hnbytes.c hnlines.c hnsamps.c hostorder.c \
	imgsize.c no_history.c sampsize.c \
	bihfree.c bih.c hbyteorder.c

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
