include $(IPW)/lib/make/Makestart

LIB=ipw

SRCS=\
	geohcheck.c geohdup.c geohmake.c geohread.c geohspace.c geohwrite.c \
	geohfree.c

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
