include $(IPW)/lib/make/Makestart

LIB=Doz

SRCS=\
	betanaught.c delted.c mwgamma.c planck.c twostream.c

OBJS := $(SRCS:%.c=%.o)

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules

