include $(IPW)/lib/make/Makestart

LIB=ipw

SRCS=\
	ephemeris.c gmt.c julday.c rotate.c sunpath.c tmconv.c unixtime.c \
	weekday.c yrday.c zonetime.c


default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
