//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SQLCNTL.RC
//
#define IDC_SQL                         1245
#define IDC_FIELDLIST                   1248
#define IDC_BETWEEN1                    1328
#define IDC_BETWEEN2                    1329
#define IDC_SAVESQL                     1457
#define IDC_LOADSQL                     1459
#define IDC_OPLIST                      1472
#define IDC_GLOBALLIST                  1473
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
