include $(IPW)/lib/make/Makestart

LIB=ipw

SRCS=\
	_hdriocb.c _hrrec.c _hwrec.c copyhdrs.c gethdrs.c hcopy.c hgetrec.c \
	hpass.c hputrec.c hrband.c hrname.c hrskip.c hrvers.c hwprmb.c \
	skiphdrs.c

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
