include $(IPW)/lib/make/Makestart

DIRS=\
	bitcom \
	cmpimg cnhist convolve \
	demux dither \
	edhdr edimg \
	flip \
	gradient grhist \
	hist histeq hor1d horizon \
	interp ipw ipw2hds ipw2ps ipw2sun ipw2xim \
	lincom lqhx lutx \
	mkbih mkgeoh mklqh mklut mksath mksunh mkwinh mstats mult mux \
	poly prhdr primg \
	random rmhdr \
	shade skew sunang \
	transpose \
	viewcalc viewf \
	wedge window \
	zoom

SUBLIBS=NO_LIBS

default: all
install: install-all

include $(IPW)/lib/make/Makerules
