include $(IPW)/lib/make/Makestart

PGM= getopt

SRCS=\
	main.c

OBJS := $(SRCS:%.c=%.o)

PGM_DIR=$(ETC_DIR)

default: pgm
install: install-pgm

include $(IPW)/lib/make/Makerules

CPP_DEFINE=
LIB_IPW=
LIB_UNIX=

