include $(IPW)/lib/make/Makestart

PGM= gradient

SRCS=\
	bihvalid.c caspect.c cslope.c diffxy.c fillends.c fillstart.c \
        gradient.c gradu.c headers.c main.c newgeoh.c newlqh.c options.c \
        shuffle.c

default: pgm
install: install-pgm

include $(IPW)/lib/make/Makerules
