static char *projnames[] = {
	"geographic",
	"Universal Transverse Mercator (UTM)",
	"State Plane Coordinates",
	"Albers Conical Equal Area",
	"Lambert Conformal Conic",
	"Mercator",
	"Polar Stereographic",
	"Polyconic",
	"Equidistant Conic",
	"Transverse Mercator",
	"Stereographic",
	"Lambert Azimuthal Equal Area",
	"Azimuthal Equidistant",
	"Gnomonic",
	"Orthographic",
	"General Vertical Near-Side Perspective",
	"Sinusiodal",
	"Equirectangular",
	"Miller Cylindrical",
	"Van der Grinten",
	"(Hotine) Oblique Mercator",
	"Space Oblique Mercator (SOM)"
};
