include $(IPW)/lib/make/Makestart

LIB=ipw

SRCS=\
	_lqh.c _lqharrays.c lqh.c lqhcheck.c lqhdup.c lqhinterp.c lqhmake.c \
	lqhread.c lqhwrite.c \
	lqhfree.c

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
