include $(IPW)/lib/make/Makestart

DIRS=\
	dempt elevrad ipw2pbm randomize refdx seq solar \
        sunlight tmpt toporad topquad twostream

SUBLIBS=NO_LIBS

default: all
install: install-all

include $(IPW)/lib/make/Makerules
