include $(IPW)/lib/make/Makestart

LIB=ipw

SRCS=\
	allocnd.c dtoa.c ecalloc.c emalloc.c frand.c ftoa.c hbit.c \
	hdralloc.c hstrdup.c imgcopy.c itoa.c ltoa.c ltof.c \
	ltoi.c ltou.c ndig.c no_tty.c ipow2.c rmlead.c rmtrail.c \
	strdup.c tdiff.c maxfiles.c

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
