//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by BASIC.RC
//
#define IDM_IMPORTWP                    101
#define IDM_ABOUT                       103
#define IDC_WPLIST                      1000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         104
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
