include $(IPW)/lib/make/Makestart

C_SPECIAL = -I$(IPW)/src/exp/ucsb/h
LIBS_SPECIAL= $(IPW)/lib/libDoz.a

PGM= twostream

SRCS=\
	main.c

default: pgm
install: install-pgm

include $(IPW)/lib/make/Makerules
