include $(IPW)/lib/make/Makestart

LIB=ipw

SRCS=\
	_bug.c __bug.c _errno.c _error.c _fderr.c _usrerr.c \
	error.c syserr.c uferr.c usrerr.c warn.c

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
