//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DBTEST.RC
//
#define IDS_FILTERALLFILES              3
#define IDM_SPLIT                       101
#define IDM_GMINSTAL                    102
#define IDM_CREATE_CMDID                103
#define IDC_MESS                        1000
#define IDC_FIND                        1001
#define IDC_FILE                        1002
#define IDC_DIR                         1003
#define IDC_RESTORE                     1004
#define IDC_FLOPPY                      1006
#define IDC_1MEG                        1007
#define IDC_3MEG                        1008
#define IDC_4MEG                        1009
#define IDC_2MEG                        1010
#define IDC_STATUS2                     1011
#define IDC_STATUS                      -1
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         104
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
