include $(IPW)/lib/make/Makestart

SCRIPT=install
SCRIPT_DIR=$(ETC_DIR)

default: 
	cp install.sh $(ETC_DIR)/install
	chmod $(SCRIPT_MODE) $(ETC_DIR)/install

install: default

include $(IPW)/lib/make/Makerules
