include $(IPW)/lib/make/Makestart


DIRS=\
	args bih error fpio geoh hdrio horh lqh main orh pixio sath skewh \
	strvec sunang sunh txtio uio util winh

default: all
install: install-all

include $(IPW)/lib/make/Makerules

