include $(IPW)/lib/make/Makestart

DIRS=\
	install ipwmake atob btoa ipwlint ipwman mc objs
# config is useful to determine correct settings of include files.
# getopt, machine, and rastool are optional

SUBLIBS=NO_LIBS

default: all
install: install-all

include $(IPW)/lib/make/Makerules
