/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_LidarDSDK_WRAP_H_
#define SWIG_LidarDSDK_WRAP_H_

class SwigDirector_ProgressDelegate : public LizardTech::ProgressDelegate, public Swig::Director {

public:
    SwigDirector_ProgressDelegate();
    virtual ~SwigDirector_ProgressDelegate();
    virtual void reportProgress(double progress);
    virtual bool getCancelled();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(double);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackreportProgress, SWIG_Callback1_t callbackgetCancelled);

private:
    SWIG_Callback0_t swig_callbackreportProgress;
    SWIG_Callback1_t swig_callbackgetCancelled;
    void swig_init_callbacks();
};


#endif
