include $(IPW)/lib/make/Makestart

LIB=ipw

SRCS=\
	_fpiocb.c _fpioinit.c fpclose.c fpfmax.c fpfmin.c fphdrs.c fpmap.c \
	fpmaplen.c fpvread.c fpvwrite.c mnxfp.c

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
