include $(IPW)/lib/make/Makestart

#C_SPECIAL=$(C_SINGLE)

PGM= viewcalc

SRCS=\
	buffers.c headers.c main.c newlqh.c parm.c trigtbl.c viewf.c

default: pgm
install: install-pgm

include $(IPW)/lib/make/Makerules
