include $(IPW)/lib/make/Makestart

LIB=ipw

SRCS=\
	_uiocb.c _uioinit.c _uread.c _uwrite.c ubof.c uclose.c ucopy.c \
	ueof.c ufilename.c ugets.c uputs.c uread.c uremove.c uropen.c \
	urskip.c ustdin.c ustdout.c uwflush.c uwopen.c uwrite.c \
	usetlevel.c ugetlevel.c

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
