#ifndef bt_h
#define bt_h

typedef	HANDLE	HGLOBAL;
#define	MAX_BTREE_LEVELS	16
typedef	struct {short 	BT_VARTYP, BT_VARLEN, BT_VAROFF;} BTVARDESC;
typedef BTVARDESC FAR	*LPBTVARDESC;



#define BT_CURPOS	20
#define BT_FIRST	21
#define BT_NEXT		22
#define BT_LAST		23
#define BT_PRIOR	24
#define BT_EQ 		31
#define BT_GT 		32
#define BT_GE 		33
#define BT_LT 		34
#define BT_LE 		35
#define BT_ANY 		36
#define BT_CHAR 	61
#define BT_REAL 	62
#define BT_INTEGER  63
#define BT_REAL4 	64
#define BT_REAL8 	65
#define BT_INT2		66
#define BT_INT4		67 
#define BT_RIGHT_CHAR 68
#define BT_NIL 		0xFFFFFFFF
#define BT_UPPER 	1
#define BT_BOTTOM 	2
#define BT_NOT_FOUND	 31
#define BT_NOT_IN_SYNC	 24
#define BT_IS_EMPTY	 	 41
#define BT_READ		0
#define BT_WRITE	1

BOOL BT_CREATE (LPSTR FNAME, int DATLEN, BOOL DATED, int NVAR, int NVAR2,
    	       LPBTVARDESC	pBtVarDesc, BOOL DUPS, int DUPPOS,
			   time_t TIME, BOOL JOURNAL);
HGLOBAL BT_OPEN (LPSTR FNAME, time_t TIME, int ACCESS, int DATE);
int BT_CLOSE(HGLOBAL IBTID);
int BT_CLOSE2(LPHANDLE pIBTID);
int BT_FIND (HGLOBAL IBTID,LPSTR KEY,int POSITION,int COND,LPSTR DATA);

int BT_PUT (HGLOBAL hBTree, LPSTR KEY,LPSTR DATA);
//int BT_PUT_NO_FIND (HGLOBAL hBTree,LPSTR KEY,LPSTR DATA, BOOL LRC, int BTST);
//void ShowBTree (HGLOBAL hBT,HWND hWnd,int DlgItem, int iPOSB);
long BT_NUM_IN_INDEX (HGLOBAL IBTID);
long BT_NUMLEVELS_IN_INDEX (HGLOBAL IBTID);
long GetBT_DATLEN (HGLOBAL IBTID);
long GetBT_LENGTH (HGLOBAL IBTID);
BOOL BT_BEING_UPDATED (HGLOBAL IBTID);
//void UMDB_UPDATE_BT_DATA (HGLOBAL IBTID,LPSTR DATA);
void BT_SET_VERSION (int V);
int BT_GET_VERSION (HGLOBAL IBTID);
HFILE GetBTFid (HGLOBAL IBTID);
BOOL BT_SET_TIME_STAMP (HGLOBAL IBTID, time_t TIME);
BOOL BT_CHECK_TIME_STAMP (HGLOBAL IBTID, time_t TIME);
int BT_DELETE(HGLOBAL IBTID,LPSTR KEY,LPSTR DATA,BOOL SECIDX);
short GetBTKeyLen (HGLOBAL IBTID);
short GetBTDataLen (HGLOBAL IBTID);
void SetReadSecIndex (HGLOBAL IBTID,BOOL val);
BOOL BT_CLEAR (HGLOBAL IBTID);
BOOL BT_CLOSEANDDELETE (LPHANDLE pIBTID);
void BT_SET_PARMS (int IMPN, int IMDN, int ISPN, int ISDN);
void DISABLE_TIME_STAMP_CHECK(void);
BOOL ReorgBTree (LPSTR Name, HWND hStatusWnd);
void BT_GETDUPDATA (LPSTR DupData,short LenDupData);
BOOL BT_GETPATHNAME (HANDLE pIBTID,LPSTR Name);
int UpdateBTCounts (HGLOBAL IBTID);
int BT_FIND_RECORD_NUMBER (HGLOBAL IBTID,long RecordNum, LPSTR KEY,LPSTR DATA);
BOOL BT_OPEN_FOR_WRITE (HGLOBAL IBTID);
//void BT_GET_DEF (HGLOBAL IBTID,LPINT DataLength,LPINT NumVar,LPBTVARDESC pVarDesc);
HANDLE BT_FormKey(HANDLE hBT, LPSTR val);

#endif





