extern	BOOL	InDisplayProcessing, HavePendingDisplay,HaveDestination;
extern	time_t	AVLStartTime;
extern	LPVIEWPORT	PrevLayerVP;   
extern	short	LayerID,TrackingStatus;    
extern	long	DisplayCycle;
extern	double	CurCLEN;     
extern	HANDLE	hOpenFileSyms, hOpenFileSymNames,hTranCopyFile;
extern	BOOL	StopCDPrompts, ReReference,AltProjLocked;
extern	POINT	CurPointLoc, CurPointF; 
extern	char	GMVersion[32];
extern	short	OutDistUnits, OutAreaUnits;
extern	HANDLE	hUpdateBuf;
extern	long	lUpdateBuf;     
extern	short	SnapEnd, SnapType;
extern	double	SnapPCT;
extern	DPOINT	SnapPoint; 
extern	POINT	PickPoint;
extern	mnmxCor	NewBounds;
extern	short	CurrentSymParent; 
extern	BOOL	CurSymIsParent,ConfigLoaded,HiPrecis;
extern	long	TotHLTPoints;
extern	char	FontNames[16][32];
extern	double	TXRot, PTRot,CurPointSize;
extern	COLORREF	IconBorderColor;
extern	HWND	hWndTraverseEntry;
extern	FARPROC lpfnTRAVERSE_ENTRYMsgProc;
extern	char	TagLocPrefix[10];    
extern	HANDLE	TagLochSaveGlobal,hNewPopups,hUserCmd,hToolCmd,hDupFiles,hDupRef,hTranReorg; 
extern	LPHANDLE	phWhichCmdList;
extern	int		TagLocMinChar;
extern	double	CurrentAZ;
extern	DPOINT	LastElementBeginPoint,LastElementEndPoint;     
extern	BOOL	InExpandIB,AlwaysUseSymDict,HaveVarFillColor;
extern	BOOL	AZLocked,WantOnlyShapePoints,IgnorePrevLayers,CheckForDupRefs,InSnap,PickAllPieces,PickOnlyEndpoints;
extern	DPOINT	PandDPoint;
extern	long	JumpBackSeg, JumpBackElement;
extern	HANDLE	hPolyBuffer,hPolyPartLen,hDisplayedRefs; 
extern	short	nPoly;
extern	int		PointRot;  
extern	HPDPOINT	lpDCurPoints;
extern	DPOINT	NewCoordPoint;
extern	FARPROC lpfnADDWAYPOINTMsgProc;    
extern	HWND	hWndAddWaypoint;
extern	LPSTR	OFTitle;  
extern	BOOL	IgnoreLbutton,UseUserPickAp,StopAtFirstInPickMacro;
extern	double	FileDistToWinDist,DeviceToScreenFactor,BaseDistToWinDist,SystemPickAp,PickApW;
extern	long	MaxDisplayPoints, MostPoints,CurSymSizeLoc,CurSymSizeLocD;
extern	short	AVLTimer,UpdateItem;
extern	long	SymbolNameLoc;
extern	short   SymbolNameLen;
extern	UINT	PatBMP[4];
extern	LPTHEME	ComputePCTTheme;
extern	MNMXCORD	EditBounds;    
extern	long	GlobalColors[10];
extern	short	ProcessSelectedTheme;
extern	short	InclusionOpt;
extern	short	ConvertMapVP, ConvertMapFileNo;
extern	short	OrthoAdjustVP, OrthoAdjustFile;
extern	double  OrthoAdjustX, OrthoAdjustY,ThemeWidthFactor;
extern	WORD	NumNewPolyPoints;
extern	HANDLE	hNewPolyPoints;
extern	HCURSOR	hDigCursor; 
extern	BOOL	CursorIsLocked,PickNET;
extern	BOOL	DisplayLinkedCursors;
extern	int		SaveDrive;
extern	RECT	PromptRect;
extern	MNMXCORD	HLTBounds;                
extern	DPOINT	CLocPoint;
extern	short	BasicDisplayItem,StartGEOSPANvp;
extern	LPSTR	lpDB, lpSQL, lpDesc, lpInsert, lpCLFile, lpCLGlob;
extern	HANDLE	hIntData,hVPToCopy;  
extern	short	NumSymbols;
extern	long	TimeRangeBeg, TimeRangeEnd;
extern	BOOL	InReset, Pickability,RedrawAfterOK;
extern	mnmxCor CurrentItemMinMax;
extern	USHORT	FileInIndex;
extern	long	LastQuadOff;
extern	short   MapVersion;
extern  HANDLE  hDesiredDocs,hStreetSegFields, hImportLimits, hGRText, hGRCommand, hTimeStamp, hAttImport;
extern	DWORD	max_check_time;    
extern	DPOINT	PickPointBase;
extern	HANDLE	hAddGraphicsFun,hReorgBUDir;
extern	POINT	CurrentLBUTDOWNLoc; 
extern	COLORREF	TempLineColor, TempFillColor, TempBackColor;
extern	HANDLE  hSavedZooms;
extern	short	FastPickFileNum;
extern	USHORT	FastPickFII;
extern	BOOL	FastPick, InGRCmd,HaveCurrentLBUTTON,CopyRec;
extern	long    StreetNum, CurPath;
extern	HANDLE	hDBStreetSegments, hPrefix, hUDI, hTEXT;
extern	RECT	CurEditRect;
extern	long	CurDescLoc;  
extern	short	CurLinkID;
extern	short	ProcessGCmdStrings;
extern	time_t	CurrentChangeDate;
extern	short	NumTAGDef;
extern	HANDLE	hTAGDef, hSpecial, hRedLine;
extern	short	lGCmdString, lTextString;
extern	HANDLE	hGCmdString, hTextString;
extern  long	PRJ_UNITS[4];
extern	DPOINT	UserSpecifiedBasePoint;
extern	BOOL	DisplayMarkers,SetRefno;
extern	HANDLE	hSavePoly; 
extern	long	nSavePoly;
extern	short	idescblock;
extern	short	DriveDir;
extern	HWND	VideoCntlWnd;
extern	HANDLE	hBTNetIntMP,hBTNetIntRef,hSelectItemsArgs;
extern	long	NetIntAT,NumPossibleRoutes;
extern	RECT	PosRouteRect;
extern	HBITMAP	PosRouteSavedScreen;
extern	BOOL	TraceNet, HaveTurnArrows;
extern	int		RouteType, NetworkID, WalkOutRouteOpt;
extern	HANDLE	hDescBlock;
extern	long	NumQuadSegs;
extern	short	NumDescBlocks;
extern	LONG	LenQuad, MaxQuadLevel, MaxQuadType,NumQuadSegsProcessed,CurGCmdStringLoc,CurSNamesLoc,CurTextStringLoc,CurTAGLoc;
extern	long	CurItemHeadLoc;
extern	short	CurlTAG;
extern	int		QuadLevelAt, QuadTypeNext;  
extern	int		ReorgStatus,ReorgFileTxt; 
extern	HWND	ReorghWnd, hWndPrompt,hWndOrthoFilter;
extern	BOOL	ReorgFile,WantQuadTree2,DisableHalt;
extern	int		NewPolyType;
extern	long	PRJ_TYPE[4];
extern	long	InternalRefno;
extern	long	CurStreetNumbers[4],FromStreet, ToStreet, CurStreet;  
extern	int		CurrentType;  
extern	HPPOINT	lpCurPoints;    
extern	BOOL	ContinueProcessing;
extern	WORD	LenQuadBlock;
extern	LONG	LenQuadSeg;
extern	HANDLE hQuadTree, hQuadOffset;
extern	BOOL	ReorgFile;
extern	BOOL CALLBACK EnumCtrlProc(HWND hCtrl,LONG lParam); 
extern	long	lBlocksRead, nBlocksRead, nBlocksIn, nBlocksOut, TotDisplayTime, DistTime, MapIOTime;
extern	BOOL	DoGraphics;
extern	BOOL	UseRefOrTAGIndex;
extern	int		FileProjectionType;
extern	BOOL	ForAllVis;
extern	long	LastRef;
extern	BOOL	PickOrtho;   
extern	HANDLE	hHighlightArea;   
extern	COLORREF	HighlightColor,ComputePCTMaskColor;
extern	int		CurrentUDILen;   
extern	BOOL	GetMaskArea,OutlineZoomArea,MaskZoomArea,IgnoreBounds,AutoClearOffset,DisableMarginPan,MaskOffsetLine;
extern	mnmxCor	MinMax, *pMinMax;
extern	int		CurrentSymNum;
extern	double	OffsetLineOffset;
extern	int		destX, destY, destW, destH, rect_width, rect_height;
extern	WORD 	bmX, bmY;
extern	HANDLE		hDibInfo, hImage;
extern	HBITMAP		hBitmap;
extern	LPBITMAPINFO	pDibInfo;
extern	float	ShadowPct, BorderPct;
extern	COLORREF	WindowColor; 
extern	HANDLE	hPDChunk;
extern	int		ShadowInc, SetVisByPar,MaxDimension;
extern	long	FirstMergeRecord, LastMergeRecord; 
extern	LPORTHO	CurOrtho;
extern	long	CurOrthoFrame;  
extern	int		OrthoID;
extern	HANDLE	hOrthos;  
extern	double	OrthoRes;
extern	long	OrthoUse;
extern	int		TSize, nBytes, MaxBrush;
extern	HRGN	hRgn;
extern	LONG	pu; 
extern	LPINT	CurElementPnt;
extern	WORD	CurElement;
extern	BOOL	PickingByRefno, Pick, FileMode, FirstError, Display, SolidAreas, ParIsVisible, Highlight;
extern	int		PltType;
extern	LONG	CurrentSeg, ItemSeg, CurrentRefno;
extern	int		CurrentDesc, CurrentiPen;
extern	WORD	CurrentItem;
extern	short	FileNum, SubFile;
extern	RECT	MainRect;
extern	HANDLE	hRefIdx,hTAGIdx,hAccelTable;
extern	BOOL	NoRefIndex,ForceRefIndex,ForceTAGIndex;
extern	long	CurrentRefno;
extern	double FileDistToBaseDist;
extern	double	WindowToFileFactor;
extern	TAGBOX	TAGBox;
extern	HCURSOR	hCursor, OldCursor;
extern	BOOL	DoPaint, HavePaint,ProcessSingleItem,ItemIsDeleted,HaveFirstHeader,DisplayOnlyHLT;
extern	HPEN	CurrentPen;
extern	HPEN	HighlightPen;
extern	HBRUSH	HighlightBrush;
extern	int		maxbrush;
extern	int		NumPicked, MaxPick; 
extern	double	PickLimit;
extern	PICKDATA	PickList[MAXPICKITEMS];
extern	double		WidthFactor;
extern	HWND	hWndMain;
extern	HWND	hInst;
extern	MNMXCORD	ZoomBoxRect;
extern	BOOL        WindowIsZoomed;
extern	long		RefMktVal;
extern  HPEN		hNullPen, hRedPen;
extern	HBRUSH		hRedBrush, hGreenBrush, hBlueBrush, hBackBrush1;
extern	LPVISLIST	CurVis;
extern	short		NumViewportsToDisplay, DisplayViewID;
extern	LPTHEME		CurTheme;
extern	LPVOID		TranFileToBase, TranBaseToFile, TranBMToBase, TranBaseToBM;
extern	HANDLE		hTranFileToBase, hTranBaseToFile, hTranBMToBase, hTranBaseToBM; 
extern	HANDLE		hTranFileToBaseOld;
extern	LPORTHO		CurOrtho;
extern	BOOL		Printing, PrintMerging;
extern	int			nPnts;
extern	int			PickAp;
extern	BOOL		UpdateSegment;
extern	BOOL		AddLBUTTON; 
extern	int		 	idTimer, Fid, FidConfig;
extern	long		UsedDescOffset,TranPointOffset, ColorPaletteOffset, GraphicsOffset, ContinuationOffset; 
extern	long		NewPrimeOffset;
extern	long		LenQuadSeg, LenQuad;
extern	long	QuadOffLoc;
extern	BOOL    MemMap, FirstMemMap, ReorgFile;   
extern  int     MemMapWidth,MemMapHeight;
extern	HANDLE	hHighlight, hHighlight2;
extern	DPOINT	CurrentPoint;
extern	double	CurrentDistance;    
extern	POINT	TXLoc;
extern	HANDLE	hCurPolyPoints;  
extern	long	nCurPolyPoints;
