#define		MAXFONTS			16
#define		MAXPICKITEMS		32
#define		MAX_FUNCTION_STACK	16
#define		MAX_VIEWPORT_FILES16	16
#define		MAX_VIEWPORT_FILES	32
#define		MAX_VPFILE_ID_v7	16
#define		MAX_VPFILE_ID		32
#define		MAX_RBUTFUN_v7		128
#define		MAX_RBUTFUN			MAX_PATH
#define     MAX_VIEWPORT_THEMES_v7 16    
#define     MAX_VIEWPORT_THEMES 32    
#define		MAX_VIEWPORTS		64 
#define		MAX_CITYNAME_LENGTH	80
#define		MAX_THEME_CLASSES_v0 16
#define		MAX_THEME_CLASSES	48  
#define		MAX_THEME_VALUE_LEN	128
#define		CUR_THEME_VERSION	4	//3 adds len to nonnum theme value list, 4 stores classno as long
#define		MAX_NEW_OBJECTS		100  
#define		MAX_DIGPOINTS		64000
#define		MAXPENS				266       
#define		MAXVEHLOC			256   
#define 	MAXREORGBUF			8*1024L*1024L
#define		MAXVARLEN			4095*4
#define		MAXDLTVAR			256
#define 	MAXSQLPERFILE   	32   
#define 	MAXTRANPOINTS		4096
#define		MAXORTHOBUFS		2 
#define		MAXCFGTAGS			32
#define		MAXOPENSURF			16   
#define		MAXDTMCELLBUFFERS	64
#define		MAXLIDARPERREC		512  
#define		LIDARCELLSIZE		4
#define		MAXNEARPOINTS		32
#define 	MAXCONTOURLINES	40000  
#define 	MAXPOINTSINCONTOUR 4090
#define		MAXSIGNATURECOLORS	16 
#define		MAXLEGENDS	64
#define		MAXCHANGES	1024
#define		MAXVEHICLES	1024
#define		MAX_SEGMENTS	1024 
#define		MAX_FENCES	256
#define		MAX_DATADISPLAYRECT	1024
#define		MAX_WAYPOINT_NAME_LENGTH	10
#define		MAX_VEHICLE_TRACK_POINTS	4096
#define		MAXPROFILEROUTES	8

                                     

#define		MAXOPENFILES    64 
#define		MAXFILESINPATH  32
#define		MAXREPORTFONTS  8  
#define		MAXREPORTFILES  16
#define		MAXREPORTTABS   8 
#define		MAXFIELDS       512 
#define		MAXGLOBALS      4096
#define		MAX_LOCAL_VARS	128
#define		MAX_CHANGED_GLOBALS 32
#define		MAXFIELDINSQL   32 
#define		MAXWHEREINCOMBO 16   
#define		MAXCFIELDINCOMBO 16
#define     MAX_GMD_INDEXES16     8 
#define     MAX_GMD_INDEXES     16 
#define     MAX_GMD_INDEX_FIELDS    8   
#define		MAX_MACRO_STACK 64
#define		MAX_BREAKPOINTS	16
#define		MAX_CMDMESSAGE USHRT_MAX

#define		MAXSAVEDSCREENS	1024  
#define		MAXBMPCACHE 64   
#define		MAXUNDOFILES	4096   
#define		MAXMULTILEVELZOOM 16     
#define		MAX_POLY_POINTS	8L * USHRT_MAX  
#define		MAX_SYMBOL_ELEMENTS 2048   
#define		MAX_ELEMENT_VECTORS 1024 
#define		MAX_SYMBOL_SIZE 4L * USHRT_MAX
#define		MAXPROFILEPOINTS	4096

#define		CURRENT_CFG_VERSION	11
#define		CURRENT_VP_VERSION	8
#define 	MAX_CFG_SIZE		1024L*1024*5L

#define		MAXWIOFFSETS	100  
#define		MAXWISEQ		4000

#define		MAX_MACRO_ARGS	16
#define		MAXARGLENGTH	SHRT_MAX

#define		MAXSAVEDIMAGES	16

#define	MAX_TOOLBARS				64
#define	MAX_TOOLBAR_CONFIGS			8
#define	MAX_TOOLBAR_CONTROLS		64
#define MAX_TOOLBAR_BUTTONS			64
#define	MAX_TOOLBAR_RADIO_BUTTONS	5
#define	MAX_TOOLBAR_TEXT_INPUT		5
#define	MAX_TOOLBAR_DROPDOWN		5
#define MAX_TOOLBAR_HOVERCMD		255
#define MAXMENUWINDOWS	32
#define MAXMENUSPERWINDOW	32
#define MAXVCLEV	32
#define MAXMODSLEN	SHRT_MAX
#define MAX_AUTOVIS_FILES	64
#define MAX_CMDMENU_COMMANDS 64

#define MAX_PREFIX_LEN	8
#define MAX_UDI_LEN	64
