BOOL GMDCopyFile (LPSTR ToFile,LPSTR FromFile,LPSTR SQL);
BOOL GWDAddIndex (LPSTR Name,HANDLE hKeyFields,int IndexType,LPMNMXCORD pBounds);
HANDLE OpenGWDatabase (LPSTR Name, short Mode);
BOOL GMDSwitchToMemFile (HANDLE hDB,int MaxMemMain,int MaxMemIndex);
void CloseGWDatabase (HANDLE DBHandle);
BOOL BasicDataDisplay (LPSTR DBName,HWND hWndDlg,short dlgitem,short nextbutton,short priorbutton,long RecNum, long iref, LPSTR pSQL,int maxline);
BOOL GetFieldIDsFromNames (LPSTR DBName,LPHANDLE phFieldIDs,LPHANDLE phFieldTypes,LPSTR FieldList,LPHANDLE phValues);
short ScanForFieldTypes (LPSTR DBName,LPHANDLE phFieldIDs,BOOL DoScan,long NumToScan);
long OutputToFile(LPSTR OutFile, BOOL Create, LPSTR DBName, LPSTR pSQL, HANDLE hFields, HANDLE hKeyFields, HANDLE hFieldTypes,HANDLE hValues, BOOL UseHLT, BOOL OutToScreen, int GMHeader, BOOL Compress, BOOL ScanForFieldTypes, long NumToScan, HWND StatusWnd, HWND hWndDlg, BOOL tabDlm);
double GetNumericFieldData (HANDLE hDB,LPFIELDINFO lpField, int FunctionID,int MultiValOption,LPSTR CmdString, long iref, int Type,LPSHORT irc,LPSTR DataFileID);
int GetCharFieldData (HANDLE hSQL,LPFIELDINFO lpField, long iref,short FunctionID,LPSTR CmdString, LPSTR Value,int maxLen,LPSTR DataFileID,int combineOption);
BOOL SetFieldValFromDlgItem (LPGWDHEADER lpGWDHead,HWND hWndDlg,UINT icntl,LPSTR FieldName);
BOOL SetFieldValFromChar(LPGWDHEADER lpGWDHead,LPGWFLDINFO lpField,LPSTR CharVal,BOOL BinMode,BOOL IncrementValue);
BOOL SetFieldValFromCharAndName(LPGWDHEADER lpGWDHead,LPSTR FieldName,LPSTR CharVal,BOOL BinMode);
BOOL SetFieldValFromLong(LPGWDHEADER lpGWDHead,LPGWFLDINFO lpGWFldInfo,long LVal);
BOOL SetFieldValFromReal(LPGWDHEADER lpGWDHead,LPGWFLDINFO lpGWFldInfo,double LVal);
BOOL GetFieldMinValue (LPGWFLDINFO lpGWFldInfo,LPVOID lpVal);
BOOL SetFieldToMinVal(LPGWDHEADER lpGWDHead,int FieldNum);
BOOL ConvertFieldValFromChar (LPGWDHEADER lpGWDHead,int FieldNum,LPSTR CharVal,LPSTR lpVal);
BOOL GWDFormKey (LPGWDHEADER lpGWDHead, int Index, BOOL Search,long length,int Month);
BOOL GMDGetFileMinMax(LPSTR FileName, LPMNMXCORD pBounds, LPINT pMinTime, LPINT pMaxTime);
BOOL GMDSetFileMinMax(LPSTR FileName, LPMNMXCORD pBounds, LPINT pMinTime, LPINT pMaxTime);
BOOL GMDUpdateMinMax(LPGWDHEADER lpGWDHead, LPDPOINT pDPoint);
HANDLE GMDKeyListFormKey(HANDLE hKeyList, LPSTR val);
BOOL LoadDLT(LPSTR DLTName, LPSTR DBName);
BOOL FAR PASCAL DISPLAY_GWD_DATAMsgProc(HWND hWndDlg, int Message, WPARAM wParam, LPARAM lParam);
BOOL FAR PASCAL GWD_INDEXESMsgProc(HWND hWndDlg, int Message, WPARAM wParam, LPARAM lParam);
BOOL FAR PASCAL COMBO_FILEMsgProc(HWND hWndDlg, int Message, WPARAM wParam, LPARAM lParam);
BOOL GMDGetNumericKeyVal (LPGWDHEADER lpGWDHead,int Index, short IndexField,double *Value);
BOOL GMDGetCharKeyVal (LPGWDHEADER lpGWDHead,int Index, short IndexField,LPSTR str);
BOOL GMDGetCharFieldVal (LPGWDHEADER lpGWDHead,int Field,LPSTR str);
int GMDGetIntegerFieldVal (LPGWDHEADER lpGWDHead,int Field);
double GMDGetRealFieldVal (LPGWDHEADER lpGWDHead,int Field);
short TestFieldVal (LPGWDHEADER lpGWDHead,int FieldNum,LPSTR lpVal,short OpCode);
//double GetNumericFieldDataAtOff (HANDLE hDB,LPFIELDINFO lpField, long Offset, LPSHORT irc);
BOOL NeedRead (LPOPENSQLDATA SQLPtr);
BOOL GWDAddField (LPSTR DBName,LPGWFLDINFO pNewFldInfo);
BOOL GetGMDUniqueFieldValues (HANDLE DBhandle, LPCSTR SQL,int fieldindex, HANDLE hDBList);
int  GWDAddRecord (LPGWDHEADER lpGWDHead,long length, LPSHORT IndexArray); 
int  GWDReplaceRecord (LPGWDHEADER lpGWDHead,long length,LPSHORT IndexArray, long Offset);
BOOL GWDDeleteRecord (LPGWDHEADER lpGWDHead,long Offset);
int  UpdateGMDFile (LPSTR File,LPSTR KeyString,LPSTR UpdateString,char Separator,BOOL Truncate,BOOL updateOnly);
BOOL FindGMDRecord (LPSTR File,LPSTR KeyString,LPSTR SetValString,short MinMatchChar,short index);
BOOL GMDCopyRecord (LPSTR File,LPSTR FromKeyString,LPSTR ToKeyString);
int DeleteGMDRecords (LPSTR File,LPSTR SQLLikeString); 
BOOL GMDFunctions (int nArgs,LPSTR *Arg,LPSTR OutLoc);
BOOL GMDReorg (LPSTR Name,int IndexToReorgOn,BOOL Compress,BOOL Verify,HWND hWnd,LPSTR AddFieldDefs);
BOOL GMDUpdateCheckPointLog (LPSTR FileName);
BOOL UpdateGMDFromCheckPointLog (HFILE FidCache,LPSTR ToFile, LPSTR FromFile);
BOOL UpdateGMDFromCheckPointLog_net (int CheckPointIDCache,HFILE FidNetTransfer,LPSTR FromFile);
int UpdateGMDFromCheckPointLog2 (LPSTR CacheFile, LPSTR FromFile,int UpdateFromCheckPointID,HFILE FidNetTransfer);
BOOL GetCacheBlock (int BlockID,HFILE FidFrom,HFILE FidTo,HFILE FidNetTransfer,int BlockSize,HWND hWndProgress,int TotBlocksToGet,int opt);
BOOL TransferCacheBlocks (int BlockID,HFILE FidFrom,HFILE FidTo,HFILE FidNetTransfer,int BlockSize,HWND hWndProgress,int TotBlocksToGet,int nseqblocks,int nblocks);
BOOL GMDCreateCheckPointLog (LPSTR FileName);
BOOL ReadDBSequential (HANDLE hDB,short Index,LPSHORT First);
BOOL DisplayFieldList (HWND hWnd,HANDLE hDB,LPRECT Rect,short type,LPSTR Title);
BOOL GetFieldList (HWND hWnd,HANDLE hDB,LPRECT rect, LPSTR Title,LPSTR Outloc);
void DestroyFieldList (void);
long FillGWDData (LPGWDHEADER lpGWDHead,long Offset);
BOOL LoadInternalGMD (LPGWDHEADER lpGWDHead,long iref);
void CreateReportFonts(LPREPORT	pReport,double Factor);
void DestroyReportFonts(LPREPORT pReport);    
int	CurrentReportFontHeight (void);
LPSTR NextRepLine (LPSTR *NextLine,LPINT LineNum); 
HANDLE OpenComboDatabase (LPSTR Name,LPSTR SQL);
BOOL CloseComboDatabase (HANDLE hDB);
BOOL CreateComboFile (LPSTR Name,LPSTR FieldDefs,LPSTR RefFile1,LPSTR RefFile2,LPSTR RefFile3,LPSTR RefFile4,LPSTR RefFile5,LPSTR RefFile6,LPSTR RefFile7,LPSTR RefFile8,LPSTR RefFile9);
BOOL GetDBFieldInfo (LPFIELDINFO pFieldInfo,HANDLE hDB);
short GetDBType (HANDLE hDB);
BOOL GWD_MergeDBs (LPSTR ToDB, LPSTR FromDB, BOOL Replace);
void AddToVarNameTable (LPSTR Name);
void DestroyVarNameTable (void);
int	SelectGWDIndex (HANDLE hFile,LPOPENSQLDATA	SQLPtr,LPSHORT pUnique);
BOOL CopyGWDatabase (LPSTR ToName, LPSTR FromName, BOOL CopyData);
BOOL GetFieldTypeAndLenFromChar (LPSTR str,LPGWFLDINFO pGWFldInfo,LPHANDLE phSetClause);
BOOL CreateGWDDatabase (LPSTR Name,int Version,BOOL Compress,int NumFields,int NumIndexFields,LPSTR DefStr);
BOOL SetGMDFileLength (int mainLen,int indexLen);
BOOL SelectFieldType (LPSTR Name,LPSTR ftype);
BOOL CreateGMTextHeader (LPFIELDINFO lpFieldInfo, LPSTR lpHead);
void GWDClearSetValues (LPGWDHEADER lpGWDHead);
BOOL GWDInitKeyValues (LPGWDHEADER lpGWDHead,int IndexToUse);
BOOL GWDInitUnsetKeyValues (LPGWDHEADER pGWDHead,int IndexToUse);
void ProcessFileSQL (LPOPENSQLDATA SQLPtr,LPOPENFILEDATA FilePtr,LPSTR SQL);
short GMDHeaderToTableDef (LPSTR DefStr,LPSTR TableDef);
BOOL GWDGetFieldInfoFromName (HANDLE hDB,LPSTR FieldName,LPGWFLDINFO pFieldInfo,LPSHORT Index);
void SetGWDCurrentOffset (LPGWDHEADER lpGWDHead,long Offset);
long FilePos (LPSTR Cmd,LPSTR FileID,LPSTR Pos,int index);
BOOL CreateGWDIndex (HANDLE hDB, LPSTR Name, short CreateIndex);
long GetGWDCurrentOffset (LPGWDHEADER lpGWDHead);
int GridFromPoint (LPGWDHEADER lpGWDHead,LPDPOINT pPoint);
long GetGMDRecordOffset(long record, BOOL UseBounds);
BOOL ValidateGMDIndexes(LPSTR FilePath);
