include $(IPW)/lib/make/Makestart

LIB=ipw

SRCS=\
	_argv.c _descrip.c _optv.c cmdline.c getargs.c opt_check.c usage.c \
	ipwgetopt.c

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
