include $(IPW)/lib/make/Makestart

C_SPECIAL= -I$(IPW)/src/exp/erlc/h

LIB=erlc

SRCS=\
	_crh.c _crharrays.c crh.c crhcheck.c crhdup.c crhmake.c crhread.c \
	crhsort.c crhwrite.c

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
