include $(IPW)/lib/make/Makestart

# C_SPECIAL     "cc" options
# LD_SPECIAL    loader options
# LINT_SPECIAL  "lint" options
 
C_SPECIAL=
LD_SPECIAL=
LINT_SPECIAL=

# LIB           library name

LIB=

# SRCS          component source files
# OBJS		is set for you automatically, so there is no need to set
#		it unless you are using non-.c files.

SRCS=\
# vi: type !!srcs here

default: lib
install: install-lib

include $(IPW)/lib/make/Makerules
