#export IPW=~ipw			# ~ doesn't work if YP passwd file
export IPW=/home/ipw			# use if ~ broken: edit for local ~ipw

export PATH=$PATH:$IPW/bin:$IPW/etc TMPDIR=/usr/tmp

# $Header: /home/ipw/pub/RCS/kshrc,v 1.2 89/11/10 16:17:30 frew Exp $
