/*
 * Copyright (c) 1990 The Regents of the University of California.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that: (1) source distributions retain this entire copyright
 * notice and comment, and (2) distributions including binaries display
 * the following acknowledgement:  ``This product includes software
 * developed by the Computer Systems Laboratory, University of
 * California, Santa Barbara and its contributors'' in the documentation
 * or other materials provided with the distribution and in all
 * advertising materials mentioning features or use of this software.
 *
 * Neither the name of the University nor the names of its contributors
 * may be used to endorse or promote products derived from this software
 * without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "ipw.h"

#include "getargs.h"

#include "poly.h"

/*
** NAME
**	poly -- print points in polygon
**
** SYNOPSIS
**	poly [-s x,y] [file]
**
** DESCRIPTION
**	poly reads polygon vertices from {file} (default: standard input)
**	and prints the line and sample coordinates of all points on the
**	polygon lines.  If the -s option is given, poly also prints the
**	coordinates of each point inside the polygon.
**
**	The input is a list of integer (x,y) coordinates, one pair per line:
**
**		x0 y0
**		x1 y1
**		...
**
**	The output is a similar list, including all points that would lie
**	on a line between each successive input coordinate pair.
**
** OPTIONS
**
**	-s	Fill the input polygon.  The input coordinates must be
**		the vertices of a closed polygon (the last coordinate
**		pair must be the same as the first), and the specified
**		{x},{y} must be inside the polygon.  The output will
**		contain all points inside the polygon, as well as all
**		points on the polygon's boundary.
**
** EXAMPLES
**	The following command:
**
**		poly
**		0 0
**		0 3
**
**	yields:
**
**		0 0
**		1 1
**		2 2
**		3 3
**
**	If "roi" contains the corners (in intrinsic line and sample
**	coordinates) of a region-of-interest, then the following command
**	will inscribe the boundaries of the region onto "image":
**
**		poly roi | edimg -i image
**
** FILES
**
** DIAGNOSTICS
**
** RESTRICTIONS
**	The output coordinates appear in order of increasing (x,y)
**	regardless of the order of the input coordinates.
**
**	Output coordinates on polygon edges are generated by a Bresenham
**	algorithm.  If -s is specified, then output coordinates inside a
**	polygon are generated by a flood-fill algorithm, using {x},{y} as
**	a seed location.
**
** FUTURE DIRECTIONS
**
** HISTORY
**	7/1/90	Written by James Frew, UCSB.
**	4/26/93	Ran through Purify.  Dana Jacobsen, ERL-C.
**
** BUGS
**
** SEE ALSO
**	IPW:  edimg
*/

void
main(argc, argv)
	int             argc;
	char          **argv;
{
	static OPTION_T opt_s = {
		's', "polygon fill seed line,sample",
		INT_OPTARGS, "coord",
		OPTIONAL, 2, 2
	};

	static OPTION_T operands = {
		OPERAND, "input vertices file",
		STR_OPERANDS, "file",
		OPTIONAL, 1, 1
	};

	static OPTION_T *optv[] = {
		&opt_s,
		&operands,
		0
	};

	FILE           *fpi;		/* input vertices file		 */
 /*
  * begin
  */
	ipwenter(argc, argv, optv, "fill polygon");
 /*
  * access files
  */
	if (!got_opt(operands)) {
		fpi = stdin;
	}
	else if (argc == 1) {
		fpi = fopen(str_arg(operands, 0), "r");
		if (fpi == NULL) {
			error("can't open \"%s\"", str_arg(operands, 0));
		}
	}
	else {
		usage();
	}
 /*
  * do it
  */
	if (got_opt(opt_s)) {
		poly(fpi, TRUE, int_arg(opt_s, 0), int_arg(opt_s, 1));
	}
	else {
		poly(fpi, FALSE, 0, 0);
	}
 /*
  * all done
  */
	ipwexit(EX_OK);
}

#ifndef	lint
static char     rcsid[] = "$Header: /local/share/pkg/ipw/src/bin/poly/RCS/main.c,v 1.2 90/11/11 17:07:41 frew Exp $";

#endif
